#### 1.목적
- iris데이터를 활용하여 그리드 서치를 적용할 수 있다

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

#### 데이터수집

In [3]:
iris = load_iris()
x = iris.data
y = iris.target

#### 데이터 전처리(편집, 생성, 스케일링)

In [4]:
# 만든 module로 스케일링 후 훈련셋, 테스트셋 나누기
import module_Score as MS


X_train, X_test, y_train, y_test = MS.ND_Standard(X=x, y=y, want_randomtate=0)

X_scaled =  np.concatenate((X_train, X_test))

In [5]:
print(X_scaled.shape)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(150, 4)
(112, 4) (112,)
(38, 4) (38,)


#### EDA

#### 모델링(모델학습, 평가)

In [6]:
param_knn = {'n_neighbors': range(1,10)}
param_knn

{'n_neighbors': range(1, 10)}

In [7]:
knn = GridSearchCV(KNeighborsClassifier(), param_knn, cv=5)
# GridSearchCV안에 cv로 교차검증이 내장되어 있음

In [8]:
knn.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 10)})

In [9]:
print(f'''
최적의 파라미터는?{knn.best_params_}
최고의 교차검증 점수?{knn.best_score_}
최고 성능 모델?{knn.best_estimator_}
       ''')


최적의 파라미터는?{'n_neighbors': 6}
최고의 교차검증 점수?0.9557312252964426
최고 성능 모델?KNeighborsClassifier(n_neighbors=6)
       


In [10]:
knn.predict(X_test), knn.score(X_test, y_test)

(array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
        0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2]),
 0.9736842105263158)

decision tree

In [14]:
from sklearn.tree import DecisionTreeRegressor

 param_dt = {'max_depth':range(1,10),
             'max_leaf_nodes': [1,2,3,4,5,6,7,8,9,10],
             'min_samples_leaf': range(1,10)
             }
 
DT = GridSearchCV(DecisionTreeRegressor(random_state=0), param_dt, cv=5)
# GridSearchCV안에 cv로 교차검증이 내장되어 있음
# DT.get_params().keys()
DT.fit(X_train, y_train)

print(f'''
최적의 파라미터는? {DT.best_params_}
최고의 교차검증 점수? {DT.best_score_}
최고 성능 모델? {DT.best_estimator_}
       ''')

DT.predict(X_test), DT.score(X_test, y_test)


최적의 파라미터는? {'max_depth': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 3}
최고의 교차검증 점수? 0.9278701527841491
최고 성능 모델? DecisionTreeRegressor(max_depth=3, max_leaf_nodes=4, min_samples_leaf=3,
                      random_state=0)
       


(array([1.97435897, 1.        , 0.        , 1.97435897, 0.        ,
        1.97435897, 0.        , 1.        , 1.        , 1.        ,
        1.97435897, 1.        , 1.        , 1.        , 1.        ,
        0.        , 1.        , 1.        , 0.        , 0.        ,
        1.75      , 1.        , 0.        , 0.        , 1.75      ,
        0.        , 0.        , 1.        , 1.        , 0.        ,
        1.97435897, 1.        , 0.        , 1.75      , 1.97435897,
        1.        , 0.        , 1.97435897]),
 0.9471327231763442)

Support Vector Machine

In [21]:
from sklearn.svm import SVC

param_svc = {'C':[0.0001, 0.001, 0.1, 0.5, 1, 10, 20, 30, 40, 50, 60],
             'gamma': [0.0001, 0.001, 0.1, 0.5, 1, 10, 20, 30, 40, 50, 60],
             'kernel': ['linear']
             }
 
SVC = GridSearchCV(SVC(), param_svc, cv=5)
# GridSearchCV안에 cv로 교차검증이 내장되어 있음
SVC.fit(X_train, y_train)

print(f'''
최적의 파라미터는? {SVC.best_params_}
최고의 교차검증 점수? {SVC.best_score_}
최고 성능 모델? {SVC.best_estimator_}
       ''')

SVC.predict(X_test), SVC.score(X_test, y_test)


최적의 파라미터는? {'C': 0.5, 'gamma': 0.0001, 'kernel': 'linear'}
최고의 교차검증 점수? 0.9640316205533598
최고 성능 모델? SVC(C=0.5, gamma=0.0001, kernel='linear')
       


(array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
        0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2]),
 0.9736842105263158)