In [183]:
import numpy as np 

In [184]:
#0이 10개 들어가 있는 array를 만들어 주세요
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [185]:
#5번째를 1로 바꿔주세요
arr[4] =1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [186]:
# 10이상 50미만의 정수가 들어가 있는 배열을 만드세여
arr = np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [187]:
# 0부터 8까지 들어간 
arr = np.arange(0,9).reshape(3,3)
print(arr)
print(np.linalg.matrix_rank(arr))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [188]:
arr = np.random.randint(1, 100, size=(3,3,3))
arr

array([[[10, 70, 13],
        [21, 71, 83],
        [10, 77, 97]],

       [[77, 73, 40],
        [75, 85,  6],
        [34, 70, 82]],

       [[10, 49,  3],
        [16, 63, 39],
        [19, 53, 64]]])

In [189]:
arr = np.random.random((3,3,3))
arr

array([[[0.34942075, 0.31895987, 0.97547893],
        [0.88681911, 0.97610778, 0.52384338],
        [0.95061646, 0.89675318, 0.31133889]],

       [[0.8951739 , 0.68298872, 0.63809099],
        [0.78662704, 0.18124837, 0.06724625],
        [0.14225674, 0.62965722, 0.81124759]],

       [[0.68608944, 0.20504689, 0.84605037],
        [0.6630732 , 0.29624285, 0.15106874],
        [0.62712383, 0.07273933, 0.759068  ]]])

In [190]:
#전체 요소가 총 30개, 그 배열의 평균값 구하기
arr = np.random.randint(1, 1000,size=(3, 10))
print(arr)
arr2 = np.random.random(30)
print("평균 :", np.mean(arr))
print("")
print(arr2)
print("요소의 개수 :", arr2.size)
print("평균 :",np.mean(arr2))

[[216 735 614 884 631 539 263 539  47 571]
 [693 576 228   3  12 865 662 818 878 777]
 [237 174 176 549 553 525 429 127  76 918]]
평균 : 477.1666666666667

[0.31895187 0.02265346 0.11767725 0.50410824 0.8590952  0.83824462
 0.80430418 0.79239186 0.54592742 0.95786509 0.36417832 0.40439772
 0.60803024 0.41617164 0.44028984 0.74917096 0.96484409 0.40742248
 0.85360923 0.53211305 0.01810434 0.62065948 0.42417449 0.14299528
 0.32182803 0.61379358 0.67995333 0.37417655 0.05545673 0.06082893]
요소의 개수 : 30
평균 : 0.493780583354547


리스트인 경우

In [191]:
mid_score = [10, 20, 30]
final_score = [70, 80, 90]
total = mid_score + final_score
print(total)

[10, 20, 30, 70, 80, 90]


배열일 경우

In [192]:
mid_score = np.array([10,20,30])
final_score = np.array([70,80,90])
total = np.array(mid_score + final_score)
print(total)
print("시험 성적의 합계 :", total)
print("시험 성적의 평균 :", total/2)

[ 80 100 120]
시험 성적의 합계 : [ 80 100 120]
시험 성적의 평균 : [40. 50. 60.]


In [193]:
array_a = np.arange(10)
array_b = np.arange(10)
array_c = np.array(range(0,10,2))

print("============array_c================")
print(array_c)
print(f"array_c의 shape : {array_c.shape}")
print(f"array_c의 ndim : {array_c.ndim}")
print(f"array_c의 size : {array_c.size}")


============array_c================
[0 2 4 6 8]
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 size : 5


In [194]:
array_c.dtype

dtype('int32')

In [195]:
#배열안에 byte크기
array_c.itemsize

4

In [196]:
salary = np.array([220, 250, 230])
salary + 100
salary * 2

array([440, 500, 460])

In [197]:
players = [[170, 76.4], [183, 86.2], [171, 73.5], [176, 80.1]]
players = np.array(players)
print(players)
print("========= 몸무게 80 이상 ===========")
# bol = np.array([False, True, False, True])
# players[bol]
s = players[:, 1] >= 80
print(s)
print(players[s])
print(players[players[:, 1] >= 80])

print("========= 키 180 이상 ===========")
print(players[players[:, 0] >= 180])

[[170.   76.4]
 [183.   86.2]
 [171.   73.5]
 [176.   80.1]]
========= 몸무게 80 이상 ===========
[False  True False  True]
[[183.   86.2]
 [176.   80.1]]
[[183.   86.2]
 [176.   80.1]]
========= 키 180 이상 ===========
[[183.   86.2]]


In [198]:
revenue_in_yen = np.random.randint(1000, 10000, size=30)
revenue_in_yen = np.floor(revenue_in_yen*0.01)*100
revenue_in_yen

array([5300., 8100., 1700., 6100., 3900., 4200., 8600., 1000., 3900.,
       9200., 4600., 7500., 6600., 6500., 5200., 7100., 9600., 9100.,
       5700., 9500., 4000., 3500., 1500., 9500., 3500., 2100., 2700.,
       3700., 8800., 1000.])

In [199]:
revenue_in_won = revenue_in_yen*9.7
revenue_in_won

array([51410., 78570., 16490., 59170., 37830., 40740., 83420.,  9700.,
       37830., 89240., 44620., 72750., 64020., 63050., 50440., 68870.,
       93120., 88270., 55290., 92150., 38800., 33950., 14550., 92150.,
       33950., 20370., 26190., 35890., 85360.,  9700.])

In [200]:
revenue_in_dollar = revenue_in_won / 1391.34
revenue_in_dollar = np.floor(revenue_in_dollar)
print(revenue_in_dollar)
print("월 매출(US)) :", np.sum(revenue_in_dollar))
print("월 매출(KR)) :", np.sum(revenue_in_won))
revenue_in_won = revenue_in_won.astype("int64")
revenue_in_won

[36. 56. 11. 42. 27. 29. 59.  6. 27. 64. 32. 52. 46. 45. 36. 49. 66. 63.
 39. 66. 27. 24. 10. 66. 24. 14. 18. 25. 61.  6.]
월 매출(US)) : 1126.0
월 매출(KR)) : 1587890.0


array([51409, 78570, 16490, 59169, 37830, 40740, 83420,  9700, 37830,
       89240, 44620, 72750, 64019, 63049, 50439, 68870, 93120, 88270,
       55289, 92150, 38800, 33950, 14549, 92150, 33950, 20370, 26189,
       35890, 85360,  9700], dtype=int64)

In [209]:
low = revenue_in_won[revenue_in_won <= 50000]
low

array([16490, 37830, 40740,  9700, 37830, 44620, 38800, 33950, 14549,
       33950, 20370, 26189, 35890,  9700], dtype=int64)

In [ ]:
for z in low:
    print(np.where(revenue_in_won == z), z)

In [202]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0),"\n")
print(np.concatenate((a, b.T), axis=1))

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]]
