In [106]:
import numpy as np

##### 몸풀기 문제

#1. 1m부터 50까지 짝수만 원소로 갖는 넘파이 배열 생성하기

In [107]:
arr = np.arange(1,51,2)
print(f"""1부터 50까지 짝수만 원소로 갖는 넘파이 배열
{arr}""")

1부터 50까지 짝수만 원소로 갖는 넘파이 배열
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


 #2.  
  0을 원소를 갖는 4x4 배열 생성  
  1을 원소를 갖는 10x10 배열 생성  
  원하는 숫자를 원소로 갖는 7x4 배열 생성  

In [108]:
arr_0 = np.zeros(16).reshape(4,4)
# arr_0 = np.zeros((4,4))
arr_1 = np.ones(100).reshape(10,10)
# arr_0 = np.ones((10,10))
arr_like = np.full((7,4),7)
print(f"""
arr_0
{arr_0}

arr_1
{arr_1}

arr_like
{arr_like}""")


arr_0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

arr_1
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

arr_like
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


#4. 1부터 100까지 원소 중 3의 배수를 원소로 갖는 배열 생성하기

In [109]:
arr_3 = np.arange(3,101,3)
print(f"""
arr_3
{arr_3}""")


arr_3
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


#5. 
1. 문제4의 배열의 요소 개수(size)
2.  2차원 배열 생성
3. 생성된 배열의 크기(shape)

In [110]:
arr_3_2 = arr_3.reshape((3,11))
print(f"""
arr_3.size : {arr_3.size}

arr_3_2
{arr_3_2}

arr_3_2.shape : {arr_3_2.shape}""")


arr_3.size : 33

arr_3_2
[[ 3  6  9 12 15 18 21 24 27 30 33]
 [36 39 42 45 48 51 54 57 60 63 66]
 [69 72 75 78 81 84 87 90 93 96 99]]

arr_3_2.shape : (3, 11)


In [111]:
arr_3_2

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66],
       [69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]])

#6. 
1. 0~1사이의 값을 랜덤하게 갖는 6*4 배열 생성   
    - random.rand(m,n) : m*n배열
2. 1~100사이의 값을 랜덤하게 갖는 5*5 배열 생성
3. astype을 사용하여 2번 배열을 실수형태의 원소로 갖는 배열 생성

In [112]:
import random

In [113]:
arr_1 =  np.random.rand(6,4)
arr_2 = np.random.randint(1,100, size=(5,5))
arr_2_float = arr_2.astype("float32")

print(f"""
arr_1
{arr_1}

arr_2
{arr_2}

arr_2_float
{arr_2_float}""")


arr_1
[[0.50811645 0.17720448 0.08371004 0.02855674]
 [0.89311358 0.02851163 0.85626797 0.6828373 ]
 [0.53440807 0.06429935 0.57812752 0.55232884]
 [0.12292307 0.12921667 0.33473865 0.32296774]
 [0.8061307  0.61281477 0.96853913 0.41055936]
 [0.99874853 0.88784258 0.51710909 0.49382564]]

arr_2
[[41 88  1 25 69]
 [97 89 65 75 11]
 [57 39  9 47 91]
 [27 99 25 46 80]
 [93 19 99 58 59]]

arr_2_float
[[41. 88.  1. 25. 69.]
 [97. 89. 65. 75. 11.]
 [57. 39.  9. 47. 91.]
 [27. 99. 25. 46. 80.]
 [93. 19. 99. 58. 59.]]


#7
1. 주어진 배열에서 3,4,8,9만 가져오기
2. 주어진 배열에서 6,7,8만 가져오기

In [114]:
x = np.arange(10).reshape(2,5)
print(f"""
주어진 배열
{x}
      
3,4,8,9만 가져오기
{x[:, 3:]}

6,7,8만 가져오기
{x[1:, 1:4]}
→ 0번째 행, 1번째 행
→ 1번째 열 ~ 4번째 열""")




주어진 배열
[[0 1 2 3 4]
 [5 6 7 8 9]]
      
3,4,8,9만 가져오기
[[3 4]
 [8 9]]

6,7,8만 가져오기
[[6 7 8]]
→ 0번째 행, 1번째 행
→ 1번째 열 ~ 4번째 열


#8
1. 3,8,13을 원소로 가져오기
2. 5,6,7,8,9를 원소로 가져오기
3. 1,2,3/ 6,7,8을 원소로 가져오기

In [115]:
y = np.arange(15).reshape(3,5)
print(f"""
주어진 배열
{y}

3,8,13을 원소로 가져오기
#방법1
{y[:, 3]}
#방법2
{y[:, 3:4]}

5,6,7,8,9를 원소로 가져오기
{y[1, :]}

1,2,3/ 6,7,8을 원소로 가져오기
{y[0:2, 1:4]}""")


주어진 배열
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

3,8,13을 원소로 가져오기
#방법1
[ 3  8 13]
#방법2
[[ 3]
 [ 8]
 [13]]

5,6,7,8,9를 원소로 가져오기
[5 6 7 8 9]

1,2,3/ 6,7,8을 원소로 가져오기
[[1 2 3]
 [6 7 8]]


#9  
1. 주어진 배열에서 5보다 작은 값만 추출
2. 주어진 배열에서 3의 배수 추출

In [116]:
arr2 = np.arange(1,13).reshape(3,4)
arr_2_3 = arr2%3
print(f"""
주어진 배열
{arr2}

5보다 작은 값만 추출
{arr2[arr2 <= 5]}

3의 배수만 추출
{arr2[arr_2_3.astype("int64") == 0]}
{arr2[arr2%3 == 0]}""")


주어진 배열
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

5보다 작은 값만 추출
[1 2 3 4 5]

3의 배수만 추출
[ 3  6  9 12]
[ 3  6  9 12]


#10-1  
1. 주어진 배열에서 2의 배수 추출
2. 주어진 배열에서 60이상인 수만 추출

In [120]:
x = np.random.randint(1,100, (10,))
print(f"""
주어진 배열
{x}

2의 배수 추출
{x[x % 2 == 0]}

60이상인 수 추출
{x[x >= 60]}""")


주어진 배열
[ 7 24 33 65 31 33 72 81 12 17]

2의 배수 추출
[24 72 12]

60이상인 수 추출
[65 72 81]


#10-2  
1. 30이상 , 70미만인 수 추출  
2. 60보다 크더나 홀수인 수 추출   
###### ** 소괄호()를 하지 않으면 오류가 날 수 있음

In [122]:
print(f"""
30이상 , 70미만인 수 추출
{x[(x >= 30) & (x < 70)]}

60보다 크더나 홀수인 수 추출
{x[(x > 60) | (x % 2 != 0)]}""")


30이상 , 70미만인 수 추출
[33 65 31 33]

60보다 크더나 홀수인 수 추출
[ 7 33 65 31 33 72 81 17]


#11  
1.  
2.  

In [124]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
len(temp)

31

In [142]:
temp_25 = temp[temp > 25.0]
print(f"""
기온이 25도를 넘는 날의 수 : {len(temp_25)}일
# 방법2 : np.sum(temp > 25) 
# → True, False로 바꿔서 그 합을 구해주는 거임
기온이 25도를 넘는 날의 평균 기온은? : {np.ceil((np.mean(temp_25)*100))/100}도""")



기온이 25도를 넘는 날의 수 : 21일
# 방법2 : np.sum(temp > 25) 
# → True, False로 바꿔서 그 합을 구해주는 거임
기온이 25도를 넘는 날의 평균 기온은? : 26.86도
