In [2]:
import numpy as np

####  Sort : 정렬하기
    - 원본이 바뀌지 않아 변수를 할당해줘야 함

1차원

In [8]:
arr = np.array([1, 10, 5,8,2,4,3,6,8,7,9])
print("1. 오름차순 np.sort(배열변수)")
print(np.sort(arr))
print("")
print("2. 내림차순 [::-1]")
print(np.sort(arr)[::-1])

1. 오름차순 np.sort(배열변수)
[ 1  2  3  4  5  6  7  8  8  9 10]

2. 내림차순 [::-1]
[10  9  8  8  7  6  5  4  3  2  1]


2차원

In [11]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])
#1. shape 확인해서 몇행 몇열인지 알기
arr2d.shape

(3, 4)

In [17]:
print(f"""
#2. 열 정렬(왼쪽에서 오른쪽으로) : np.sort(arr2d, axis=1)
{np.sort(arr2d, axis=1)}

#3. 행 정렬(위에서 아래로) : np.sort(arr2d, axis = 0)
{np.sort(arr2d, axis = 0)}
""")


#2. 열 정렬(왼쪽에서 오른쪽으로) : np.sort(arr2d, axis=1)
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]

#3. 행 정렬(위에서 아래로) : np.sort(arr2d, axis = 0)
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]



#### 최대, 최소값, 분산(var), 중앙값(median), 표준편차(std) 

In [19]:
y = np.random.randint(100, size = (3,5))
print(y)

[[29 65 59 53 67]
 [42 41  3 54 77]
 [92 48 75 80 78]]


In [24]:
print(f"""
#1. 평균 : np.mean(y) = {np.mean(y)}
#2. 합 : np.sum(y) = {np.sum(y)}
#3. 최대값 : np.max(y) = {np.max(y)}
#4. 최소값 : np.min(y) = {np.min(y)}
#5. 분산 : np.var(y) = {np.var(y)}
#6. 중앙값 : np.median(y) = {np.median(y)}
#7. 표준편차 : np.std(y) = {np.std(y)}
""")


#1. 평균 : np.mean(y) = 57.53333333333333
#2. 합 : np.sum(y) = 863
#3. 최대값 : np.max(y) = 92
#4. 최소값 : np.min(y) = 3
#5. 분산 : np.var(y) = 491.31555555555565
#6. 중앙값 : np.median(y) = 59.0
#7. 표준편차 : np.std(y) = 22.165639073926013

