In [47]:
import numpy as np

##### #1. BMI구하기  
1. 텍스트 불러오기  
: np.loadtxt("height_weight.txt", delimiter = ",")  
    구분기호 : delimiter = "원하는 기호"

In [48]:
#1. 텍스트 파일 불러오기
data = np.loadtxt("height_weight.txt", delimiter = ",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [49]:
#2. shape을 통해 총 10명의 정보라는 것을 알 수 있음
data.shape


(2, 10)

In [50]:
#3. 테이터를 키와 몸무게로 나누기
height_cm = data[0]
weight_kg = data[1]
height_m = height_cm/100
BMI = weight_kg/(height_m * height_m)

print(f"""
height_cm
{height_cm}

height_m
{height_m}

weight_kg
{weight_kg}

BMI
{BMI}
""")


height_cm
[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]

height_m
[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]

weight_kg
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]

BMI
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]



##### #2.   
1. 텍스트 불러오기  
: np.loadtxt("ratings.txt", delimiter = "::", dtype = "int") 
    - 정수로 못 불러올 수도 있으니까 dtype = "int" 

In [51]:
ratings = np.loadtxt("ratings.txt", delimiter = "::", dtype="int") 
len(ratings)

1000209

In [52]:
#2. 정보 확인
user_1 = ratings[ratings[:, 0]==1]

print(f"""
#2-1. 크기 확인 : {ratings.shape}
#2-2. 차원 확인 : {ratings.ndim}
#2-3. 원소개수 확인 : {ratings.size}
#2-4. 1번 유저의 정보
{ratings[ratings[:, 0]==1]}
""")


#2-1. 크기 확인 : (1000209, 4)
#2-2. 차원 확인 : 2
#2-3. 원소개수 확인 : 4000836
#2-4. 1번 유저의 정보
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1  

In [69]:
print(f"""
아이디 정보 가져오기
{ratings[:, 0]}
전체사용자의 평균 평점
{np.ceil((np.mean(ratings[:, 2])*1000))/1000}
1번사용자의 평균 평점
{np.ceil((np.mean(user_1[:, 2])*1000))/1000}
""")


아이디 정보 가져오기
[   1    1    1 ... 6040 6040 6040]
전체사용자의 평균 평점
3.582
1번사용자의 평균 평점
4.189

